customhost = "empdatabase-12.cwzcccaqrmsz.us-east-1.rds.amazonaws.com"
customuser = "Ashman"
custompass = "Ashman97"
customdb = "empdatabase-12"
custombucket = "employeesadd"
customregion = "us-east-1"
